# Generated by Django 6.0.6 on 2026-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/portfolio/thumbnails/'),
        ),
    ]
